services:
  - type: web
    name: juridico-mvp
    env: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PUPPETEER_CACHE_DIR
        value: /opt/render/.cache/puppeteer
